In [ ]:
int gy[3][3][3],gx[3][3][3],gz[3][3][3];
int hx[3]={1,2,1},hy[3]={1,2,1},hz[3]={1,2,1};
int hpx[3]={1,0,-1},hpy[3]={1,0,-1},hpz[3]={1,0,-1};
int sumx,sumy,sumz;
int m,n,k;

for(m=0;m<=2;m++) //build the kernel
 for(n=0;n<=2;n++)
   for(k=0;k<=2;k++){
	gx[m][n][k]=hpx[m]*hy[n]*hz[k];
	gy[m][n][k]=hx[m]*hpy[n]*hz[k];
	gz[m][n][k]=hx[m]*hy[n]*hpz[k];

In [2]:
import numpy as np

mask_x = [[[-1,0,1], [-2,0,2], []], 
          [[], [], []],
          [[], [], []]]
mask_y = [[[], [], []], 
          [[], [], []],
          [[], [], []]]
mask_z = [[[1,2,1], [2,4,2], [1,2,1]], 
          [[0,0,0], [0,0,0], [0,0,0]],
          [[-1,-2,-1], [-2,-4,-2], [-1,-2,-1]]]

[[[1, 2, 1], [2, 4, 2], [1, 2, 1]], [[0, 0, 0], [0, 0, 0], [0, 0, 0]], [[-1, -2, -1], [-2, -4, -2], [-1, -2, -1]]]


In [8]:
h = [1, 2, 1]
h_p = [1, 0, -1]

mask_x = np.zeros((3, 3, 3))
mask_y = np.zeros((3, 3, 3))
mask_z = np.zeros((3, 3, 3))
print(mask_x)

for i in range(3):
    for j in range(3):
        for k in range (3):
            mask_x[i][j][k] = h_p[i] * h[j] * h[k]
            mask_y[i][j][k] = h[i] * h_p[j] * h[k]
            mask_z[i][j][k] = h[i] * h[j] * h_p[k]
            
print(mask_x)   
print(mask_y)
print(mask_z)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
[[[ 1.  2.  1.]
  [ 2.  4.  2.]
  [ 1.  2.  1.]]

 [[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[-1. -2. -1.]
  [-2. -4. -2.]
  [-1. -2. -1.]]]
[[[ 1.  2.  1.]
  [ 0.  0.  0.]
  [-1. -2. -1.]]

 [[ 2.  4.  2.]
  [ 0.  0.  0.]
  [-2. -4. -2.]]

 [[ 1.  2.  1.]
  [ 0.  0.  0.]
  [-1. -2. -1.]]]
[[[ 1.  0. -1.]
  [ 2.  0. -2.]
  [ 1.  0. -1.]]

 [[ 2.  0. -2.]
  [ 4.  0. -4.]
  [ 2.  0. -2.]]

 [[ 1.  0. -1.]
  [ 2.  0. -2.]
  [ 1.  0. -1.]]]


In [ ]:
int kx[3][3][3] = {{{-1,-2,-1},{0,0,0},{1,2,1}},
  {{-2,-4,-2},{0,0,0},{2,4,2}},
  {{-1,-2,-1},{0,0,0},{1,2,1}}}; 
int ky[3][3][3] = {{{-1,-2,-1},{-2,-4,-2},{-1,-2,-1}},
      {{0,0,0},{0,0,0},{0,0,0}},
      {{1,2,1},{2,4,2},{1,2,1}}}; 
int kz[3][3][3] = {{{-1,0,1},{-2,0,2},{-1,0,1}},
      {{-2,0,2},{-4,0,4},{-2,0,2}},
      {{-1,0,1},{-1,0,1},{-1,0,1}}};